version: "3"
services:
  ganache:
    image: famvcucu/eth-ganache:latest
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
  dapp:
    image: famvcucu/eth-server:latest
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - ganache

  react:
    image: famvcucu/eth-react:latest
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - dapp
